#!/usr/bin/env node
// download-famous.js — 名画100選 画像DL + JSON生成
// GitHub Actions上で実行。Wikimediaからダウンロードしてpublic/images/famous/に保存

const fs   = require('fs');
const path = require('path');
const https = require('https');

const OUT_IMG  = path.join(__dirname, '..', 'public', 'images', 'famous');
const OUT_JSON = path.join(__dirname, '..', 'public', 'famous100.json');

if (!fs.existsSync(OUT_IMG)) fs.mkdirSync(OUT_IMG, { recursive: true });

function download(url, dest) {
  return new Promise((resolve, reject) => {
    // 既存ファイルが10KB以上あればスキップ
    if (fs.existsSync(dest) && fs.statSync(dest).size > 10000) {
      console.log(`  [SKIP] ${path.basename(dest)}`);
      return resolve(true);
    }
    const file = fs.createWriteStream(dest);
    const req = https.get(url, {
      headers: {
        'User-Agent': 'MeigaBot/1.0 (https://meiga.vercel.app; educational use; contact via GitHub)',
        'Accept': 'image/webp,image/jpeg,image/*',
      }
    }, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        file.close();
        fs.unlinkSync(dest);
        return download(res.headers.location, dest).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        file.close();
        if (fs.existsSync(dest)) fs.unlinkSync(dest);
        return reject(new Error(`HTTP ${res.statusCode}`));
      }
      res.pipe(file);
      file.on('finish', () => { file.close(); resolve(true); });
    });
    req.setTimeout(20000, () => { req.abort(); reject(new Error('timeout')); });
    req.on('error', (e) => { file.close(); if (fs.existsSync(dest)) fs.unlinkSync(dest); reject(e); });
  });
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// ─── 名画100選リスト ──────────────────────────────────────────────────────────
const FAMOUS100 = [
  // ─ イタリア・ルネサンス ─
  { id:'f-001', title:'モナ・リザ',               artist:'レオナルド・ダ・ヴィンチ', year:1503, century:'16世紀', theme:'人物画',  museum:'ルーヴル美術館',           museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010062370', wikiUrl:'https://ja.wikipedia.org/wiki/モナ・リザ',                       file:'mona_lisa.jpg',              src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/800px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg' },
  { id:'f-002', title:'最後の晩餐',               artist:'レオナルド・ダ・ヴィンチ', year:1498, century:'15世紀', theme:'宗教画',  museum:'サンタ・マリア・デッレ・グラツィエ教会', museumUrl:'https://cenacolovinciano.org/en/', wikiUrl:'https://ja.wikipedia.org/wiki/最後の晩餐_(レオナルド・ダ・ヴィンチ)', file:'last_supper.jpg',           src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/%22The_Last_Supper%22_-_Leonardo_Da_Vinci_-_S._Maria_delle_Grazie_-_Milan_2016.jpg/1280px-%22The_Last_Supper%22_-_Leonardo_Da_Vinci_-_S._Maria_delle_Grazie_-_Milan_2016.jpg' },
  { id:'f-003', title:'受胎告知',                 artist:'レオナルド・ダ・ヴィンチ', year:1475, century:'15世紀', theme:'宗教画',  museum:'ウフィツィ美術館',           museumUrl:'https://www.uffizi.it/opere/annunciazione-leonardo',       wikiUrl:'https://ja.wikipedia.org/wiki/受胎告知_(レオナルド・ダ・ヴィンチ)', file:'annunciation_leonardo.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Leonardo_da_Vinci_-_Annunciazione_-_Google_Art_Project.jpg/1280px-Leonardo_da_Vinci_-_Annunciazione_-_Google_Art_Project.jpg' },
  { id:'f-004', title:'岩窟の聖母',               artist:'レオナルド・ダ・ヴィンチ', year:1486, century:'15世紀', theme:'宗教画',  museum:'ルーヴル美術館',           museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010062370', wikiUrl:'https://ja.wikipedia.org/wiki/岩窟の聖母',                       file:'virgin_of_rocks.jpg',       src:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Leonardo_da_Vinci_-_Virgin_of_the_Rocks_%28Louvre%29.jpg/800px-Leonardo_da_Vinci_-_Virgin_of_the_Rocks_%28Louvre%29.jpg' },
  { id:'f-005', title:'ヴィーナスの誕生',         artist:'サンドロ・ボッティチェッリ', year:1485, century:'15世紀', theme:'神話', museum:'ウフィツィ美術館',           museumUrl:'https://www.uffizi.it/opere/nascita-di-venere',           wikiUrl:'https://ja.wikipedia.org/wiki/ヴィーナスの誕生_(ボッティチェッリ)', file:'birth_of_venus.jpg',       src:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1024px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg' },
  { id:'f-006', title:'春（プリマヴェーラ）',     artist:'サンドロ・ボッティチェッリ', year:1482, century:'15世紀', theme:'神話', museum:'ウフィツィ美術館',           museumUrl:'https://www.uffizi.it/opere/primavera',                   wikiUrl:'https://ja.wikipedia.org/wiki/春_(ボッティチェッリ)',               file:'primavera.jpg',             src:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Botticelli-primavera.jpg/1024px-Botticelli-primavera.jpg' },
  { id:'f-007', title:'アテナイの学堂',           artist:'ラファエロ・サンティ',       year:1511, century:'16世紀', theme:'歴史画', museum:'バチカン美術館',          museumUrl:'https://www.museivaticani.va/content/museivaticani/en/collezioni/musei/stanze-di-raffaello.html', wikiUrl:'https://ja.wikipedia.org/wiki/アテナイの学堂', file:'school_of_athens.jpg',    src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/1280px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg' },
  { id:'f-008', title:'システィーナの聖母',       artist:'ラファエロ・サンティ',       year:1512, century:'16世紀', theme:'宗教画', museum:'ドレスデン国立美術館',    museumUrl:'https://www.skd.museum/en/museums-institutions/gemaldegalerie-alte-meister/', wikiUrl:'https://ja.wikipedia.org/wiki/システィーナの聖母', file:'sistine_madonna.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Raffael_-_Sixtinische_Madonna.jpg/800px-Raffael_-_Sixtinische_Madonna.jpg' },
  { id:'f-009', title:'聖家族（ドーニの円形画）', artist:'ミケランジェロ・ブオナローティ', year:1507, century:'16世紀', theme:'宗教画', museum:'ウフィツィ美術館', museumUrl:'https://www.uffizi.it/opere/tondo-doni',                   wikiUrl:'https://ja.wikipedia.org/wiki/ドーニのトンド',                     file:'doni_tondo.jpg',            src:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Michelangelo%2C_Doni_tondo%2C_1506-1508%2C_02.jpg/800px-Michelangelo%2C_Doni_tondo%2C_1506-1508%2C_02.jpg' },
  // ─ フランドル・オランダ ─
  { id:'f-010', title:'夜警',                     artist:'レンブラント・ファン・レイン', year:1642, century:'17世紀', theme:'人物画', museum:'アムステルダム国立美術館', museumUrl:'https://www.rijksmuseum.nl/en/collection/SK-C-5',         wikiUrl:'https://ja.wikipedia.org/wiki/夜警',                               file:'night_watch.jpg',           src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Rembrandt_van_Rijn_-_The_Night_Watch_-_Google_Art_Project.jpg/1024px-Rembrandt_van_Rijn_-_The_Night_Watch_-_Google_Art_Project.jpg' },
  { id:'f-011', title:'テュルプ博士の解剖学講義', artist:'レンブラント・ファン・レイン', year:1632, century:'17世紀', theme:'人物画', museum:'マウリッツハイス美術館', museumUrl:'https://www.mauritshuis.nl/en/our-collection/artworks/146-the-anatomy-lesson-of-dr-nicolaes-tulp/', wikiUrl:'https://ja.wikipedia.org/wiki/テュルプ博士の解剖学講義', file:'anatomy_lesson.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg/1280px-The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg' },
  { id:'f-012', title:'自画像',                   artist:'レンブラント・ファン・レイン', year:1660, century:'17世紀', theme:'人物画', museum:'メトロポリタン美術館',   museumUrl:'https://www.metmuseum.org/art/collection/search/437397',  wikiUrl:'https://ja.wikipedia.org/wiki/レンブラント・ファン・レインの自画像', file:'rembrandt_self_portrait.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg/800px-Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg' },
  { id:'f-013', title:'真珠の耳飾りの少女',       artist:'ヨハネス・フェルメール',     year:1665, century:'17世紀', theme:'人物画', museum:'マウリッツハイス美術館', museumUrl:'https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring/', wikiUrl:'https://ja.wikipedia.org/wiki/真珠の耳飾りの少女', file:'girl_pearl_earring.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/800px-1665_Girl_with_a_Pearl_Earring.jpg' },
  { id:'f-014', title:'牛乳を注ぐ女',             artist:'ヨハネス・フェルメール',     year:1658, century:'17世紀', theme:'日常',   museum:'アムステルダム国立美術館', museumUrl:'https://www.rijksmuseum.nl/en/collection/SK-A-2344',     wikiUrl:'https://ja.wikipedia.org/wiki/牛乳を注ぐ女',                       file:'milkmaid_vermeer.jpg',      src:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg/800px-Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg' },
  { id:'f-015', title:'デルフトの眺望',           artist:'ヨハネス・フェルメール',     year:1661, century:'17世紀', theme:'風景画', museum:'マウリッツハイス美術館', museumUrl:'https://www.mauritshuis.nl/en/our-collection/artworks/92-view-of-delft/', wikiUrl:'https://ja.wikipedia.org/wiki/デルフトの眺望', file:'view_of_delft.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vermeer-view-of-delft.jpg/1280px-Vermeer-view-of-delft.jpg' },
  { id:'f-016', title:'アルノルフィーニ夫妻の肖像', artist:'ヤン・ファン・エイク',    year:1434, century:'15世紀', theme:'人物画', museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/jan-van-eyck-the-arnolfini-portrait', wikiUrl:'https://ja.wikipedia.org/wiki/アルノルフィーニ夫妻の肖像', file:'arnolfini_portrait.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/800px-Van_Eyck_-_Arnolfini_Portrait.jpg' },
  { id:'f-017', title:'農民の婚礼',               artist:'ピーテル・ブリューゲル（父）', year:1567, century:'16世紀', theme:'日常', museum:'美術史美術館',             museumUrl:'https://www.khm.at/objektdb/detail/1016/',                wikiUrl:'https://ja.wikipedia.org/wiki/農民の婚礼_(ブリューゲル)',             file:'peasant_wedding.jpg',       src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Pieter_Bruegel_the_Elder-_The_Peasant_Wedding.JPG/1280px-Pieter_Bruegel_the_Elder-_The_Peasant_Wedding.JPG' },
  { id:'f-018', title:'バベルの塔',               artist:'ピーテル・ブリューゲル（父）', year:1563, century:'16世紀', theme:'幻想', museum:'美術史美術館',             museumUrl:'https://www.khm.at/objektdb/detail/1026/',                wikiUrl:'https://ja.wikipedia.org/wiki/バベルの塔_(絵画)',                   file:'tower_of_babel.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project.jpg/1024px-Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project.jpg' },
  { id:'f-019', title:'快楽の園',                 artist:'ヒエロニムス・ボス',         year:1510, century:'16世紀', theme:'幻想', museum:'プラド美術館',             museumUrl:'https://www.museodelprado.es/en/the-collection/art-work/the-garden-of-earthly-delights-triptych/02388242-6d6a-4e9e-a992-e1311eab3609', wikiUrl:'https://ja.wikipedia.org/wiki/快楽の園', file:'garden_earthly_delights.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_Garden_of_earthly_delights.jpg/1280px-The_Garden_of_earthly_delights.jpg' },
  { id:'f-020', title:'三美神',                   artist:'ピーテル・パウル・ルーベンス', year:1635, century:'17世紀', theme:'神話', museum:'プラド美術館',            museumUrl:'https://www.museodelprado.es/en/the-collection/art-work/the-three-graces/145e3519-8b1f-4659-bcc5-5b3afc83d4de', wikiUrl:'https://ja.wikipedia.org/wiki/三美神_(ルーベンス)', file:'three_graces_rubens.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Las_tres_Gracias%2C_by_Peter_Paul_Rubens%2C_from_Prado_in_Google_Earth.jpg/800px-Las_tres_Gracias%2C_by_Peter_Paul_Rubens%2C_from_Prado_in_Google_Earth.jpg' },
  { id:'f-021', title:'大使たち',                 artist:'ハンス・ホルバイン（子）',   year:1533, century:'16世紀', theme:'人物画', museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/hans-holbein-the-younger-the-ambassadors', wikiUrl:'https://ja.wikipedia.org/wiki/大使たち_(絵画)', file:'the_ambassadors.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg/1024px-Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg' },
  // ─ イタリア・バロック ─
  { id:'f-022', title:'バッカス',                 artist:'カラヴァッジョ',             year:1596, century:'16世紀', theme:'神話',  museum:'ウフィツィ美術館',           museumUrl:'https://www.uffizi.it/opere/bacco',                       wikiUrl:'https://ja.wikipedia.org/wiki/バッカス_(カラヴァッジョ)',             file:'bacchus_caravaggio.jpg',    src:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Caravaggio_-_Bacco_%28Michelangelo_Merisi%29_-_Google_Art_Project.jpg/800px-Caravaggio_-_Bacco_%28Michelangelo_Merisi%29_-_Google_Art_Project.jpg' },
  { id:'f-023', title:'音楽家たち',               artist:'カラヴァッジョ',             year:1597, century:'17世紀', theme:'日常',  museum:'メトロポリタン美術館',       museumUrl:'https://www.metmuseum.org/art/collection/search/435844',  wikiUrl:'https://ja.wikipedia.org/wiki/音楽家たち_(カラヴァッジョ)',           file:'musicians_caravaggio.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Michelangelo_Merisi_da_Caravaggio_-_The_Musicians_-_Google_Art_Project.jpg/1024px-Michelangelo_Merisi_da_Caravaggio_-_The_Musicians_-_Google_Art_Project.jpg' },
  { id:'f-024', title:'エマオの晩餐',             artist:'カラヴァッジョ',             year:1601, century:'17世紀', theme:'宗教画', museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/michelangelo-merisi-da-caravaggio-the-supper-at-emmaus', wikiUrl:'https://ja.wikipedia.org/wiki/エマオの晩餐_(カラヴァッジョ)', file:'supper_emmaus.jpg',         src:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/0_The_Supper_at_Emmaus_-_Caravaggio_%281601%29_-_National_Gallery_London.jpg/1280px-0_The_Supper_at_Emmaus_-_Caravaggio_%281601%29_-_National_Gallery_London.jpg' },
  { id:'f-025', title:'ユディトとホロフェルネス', artist:'アルテミジア・ジェンティレスキ', year:1620, century:'17世紀', theme:'宗教画', museum:'ウフィツィ美術館',    museumUrl:'https://www.uffizi.it/opere/giuditta-e-oloferne-artemisia', wikiUrl:'https://ja.wikipedia.org/wiki/ユディトとホロフェルネス_(アルテミジア・ジェンティレスキ)', file:'judith_holofernes.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Artemisia_Gentileschi_-_Judith_Slaying_Holofernes_%28Uffizi%29.jpg/800px-Artemisia_Gentileschi_-_Judith_Slaying_Holofernes_%28Uffizi%29.jpg' },
  // ─ スペイン ─
  { id:'f-026', title:'ラス・メニーナス',         artist:'ディエゴ・ベラスケス',       year:1656, century:'17世紀', theme:'人物画', museum:'プラド美術館',           museumUrl:'https://www.museodelprado.es/en/the-collection/art-work/las-meninas/9fdc7800-9ade-48b0-ab8b-edee94ea877f', wikiUrl:'https://ja.wikipedia.org/wiki/ラス・メニーナス', file:'las_meninas.jpg',          src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Las_Meninas_01.jpg/800px-Las_Meninas_01.jpg' },
  { id:'f-027', title:'1808年5月3日の銃殺',       artist:'フランシスコ・ゴヤ',         year:1814, century:'19世紀', theme:'歴史画', museum:'プラド美術館',           museumUrl:'https://www.museodelprado.es/en/the-collection/art-work/the-third-of-may-1808/5e44872c-6d7e-4bf9-9a3a-44d54f7eeb3b', wikiUrl:'https://ja.wikipedia.org/wiki/1808年5月3日の処刑', file:'third_of_may.jpg',         src:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_in_Google_Earth.jpg/1280px-El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_in_Google_Earth.jpg' },
  { id:'f-028', title:'裸のマハ',                 artist:'フランシスコ・ゴヤ',         year:1800, century:'19世紀', theme:'人物画', museum:'プラド美術館',           museumUrl:'https://www.museodelprado.es/en/the-collection/art-work/the-nude-maja/65953b93-3a4c-4d81-8db6-3e6965e44ba4', wikiUrl:'https://ja.wikipedia.org/wiki/裸のマハ', file:'maja_desnuda.jpg',          src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/La_Maja_Desnuda_-_Francisco_Goya.jpg/1280px-La_Maja_Desnuda_-_Francisco_Goya.jpg' },
  { id:'f-029', title:'我が子を食らうサトゥルヌス', artist:'フランシスコ・ゴヤ',       year:1823, century:'19世紀', theme:'神話',  museum:'プラド美術館',           museumUrl:'https://www.museodelprado.es/en/the-collection/art-work/saturn/18110044-7a5b-4497-84e3-799e47d23e8c', wikiUrl:'https://ja.wikipedia.org/wiki/我が子を食らうサトゥルヌス', file:'saturn_devouring.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/800px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg' },
  // ─ ティツィアーノ ─
  { id:'f-030', title:'ヴィーナスとアドニス',     artist:'ティツィアーノ・ヴェチェッリオ', year:1554, century:'16世紀', theme:'神話', museum:'プラド美術館',          museumUrl:'https://www.museodelprado.es/en/the-collection/art-work/venus-and-adonis/6e9a19de-e5ce-47f8-accc-19af4ac60cb8', wikiUrl:'https://ja.wikipedia.org/wiki/ヴィーナスとアドニス_(ティツィアーノ)', file:'venus_adonis_titian.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Tizian_088.jpg/1024px-Tizian_088.jpg' },
  { id:'f-031', title:'バッカスとアリアドネ',     artist:'ティツィアーノ・ヴェチェッリオ', year:1523, century:'16世紀', theme:'神話', museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/titian-bacchus-and-ariadne', wikiUrl:'https://ja.wikipedia.org/wiki/バッカスとアリアドネ_(ティツィアーノ)', file:'bacchus_ariadne.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Titian_Bacchus_and_Ariadne.jpg/1280px-Titian_Bacchus_and_Ariadne.jpg' },
  // ─ フランス新古典・ロマン派 ─
  { id:'f-032', title:'ソクラテスの死',           artist:'ジャック＝ルイ・ダヴィッド', year:1787, century:'18世紀', theme:'歴史画', museum:'メトロポリタン美術館',   museumUrl:'https://www.metmuseum.org/art/collection/search/436105',  wikiUrl:'https://ja.wikipedia.org/wiki/ソクラテスの死_(ダヴィッド)',           file:'death_of_socrates.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/David_-_The_Death_of_Socrates.jpg/1280px-David_-_The_Death_of_Socrates.jpg' },
  { id:'f-033', title:'マラーの死',               artist:'ジャック＝ルイ・ダヴィッド', year:1793, century:'18世紀', theme:'歴史画', museum:'ベルギー王立美術館',      museumUrl:'https://fine-arts-museum.be/en/the-collections/jacques-louis-david-the-death-of-marat', wikiUrl:'https://ja.wikipedia.org/wiki/マラーの死', file:'death_of_marat.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Death_of_Marat_by_David.jpg/800px-Death_of_Marat_by_David.jpg' },
  { id:'f-034', title:'ナポレオンの戴冠式',       artist:'ジャック＝ルイ・ダヴィッド', year:1807, century:'19世紀', theme:'歴史画', museum:'ルーヴル美術館',           museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010062975', wikiUrl:'https://ja.wikipedia.org/wiki/ナポレオンの戴冠式',                   file:'coronation_napoleon.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Jacques-Louis_David_-_The_Coronation_of_Napoleon_%281807%29.jpg/1280px-Jacques-Louis_David_-_The_Coronation_of_Napoleon_%281807%29.jpg' },
  { id:'f-035', title:'ホラティウス兄弟の誓い',   artist:'ジャック＝ルイ・ダヴィッド', year:1784, century:'18世紀', theme:'歴史画', museum:'ルーヴル美術館',           museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010065536', wikiUrl:'https://ja.wikipedia.org/wiki/ホラティウス兄弟の誓い',               file:'oath_horatii.jpg',          src:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/David_Oath_of_the_Horatii.jpg/1280px-David_Oath_of_the_Horatii.jpg' },
  { id:'f-036', title:'民衆を導く自由の女神',     artist:'ウジェーヌ・ドラクロワ',     year:1830, century:'19世紀', theme:'歴史画', museum:'ルーヴル美術館',           museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010065872', wikiUrl:'https://ja.wikipedia.org/wiki/民衆を導く自由の女神',                 file:'liberty_leading.jpg',       src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg/1280px-Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg' },
  { id:'f-037', title:'キオス島の虐殺',           artist:'ウジェーヌ・ドラクロワ',     year:1824, century:'19世紀', theme:'歴史画', museum:'ルーヴル美術館',           museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010064059', wikiUrl:'https://ja.wikipedia.org/wiki/キオス島の虐殺',                       file:'massacre_chios.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Eug%C3%A8ne_Delacroix_-_Le_Massacre_de_Scio.jpg/800px-Eug%C3%A8ne_Delacroix_-_Le_Massacre_de_Scio.jpg' },
  { id:'f-038', title:'メデューズ号の筏',         artist:'テオドール・ジェリコー',     year:1819, century:'19世紀', theme:'歴史画', museum:'ルーヴル美術館',           museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010073497', wikiUrl:'https://ja.wikipedia.org/wiki/メデューズ号の筏',                     file:'raft_of_medusa.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg/1280px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_%28Museo_del_Louvre%2C_1818-19%29.jpg' },
  { id:'f-039', title:'グランド・オダリスク',     artist:'ジャン＝オーギュスト＝ドミニク・アングル', year:1814, century:'19世紀', theme:'人物画', museum:'ルーヴル美術館', museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010062975', wikiUrl:'https://ja.wikipedia.org/wiki/グランド・オダリスク', file:'grande_odalisque.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/La_Grande_Odalisque_MNAV.jpg/1280px-La_Grande_Odalisque_MNAV.jpg' },
  // ─ イギリス ─
  { id:'f-040', title:'戦艦テメレール号',         artist:'ジョゼフ・マロード・ウィリアム・ターナー', year:1839, century:'19世紀', theme:'風景画', museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/joseph-mallord-william-turner-the-fighting-temeraire', wikiUrl:'https://ja.wikipedia.org/wiki/戦艦テメレール号', file:'fighting_temeraire.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Turner%2C_J._M._W._-_The_Fighting_Temeraire_tugged_to_her_Last_Berth_to_be_broken_Up.jpg/1280px-Turner%2C_J._M._W._-_The_Fighting_Temeraire_tugged_to_her_Last_Berth_to_be_broken_Up.jpg' },
  { id:'f-041', title:'雨・蒸気・速度',           artist:'ジョゼフ・マロード・ウィリアム・ターナー', year:1844, century:'19世紀', theme:'風景画', museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/joseph-mallord-william-turner-rain-steam-and-speed-the-great-western-railway', wikiUrl:'https://ja.wikipedia.org/wiki/雨、蒸気、速度', file:'rain_steam_speed.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Turner_-_Rain%2C_Steam_and_Speed_-_National_Gallery_file.jpg/1280px-Turner_-_Rain%2C_Steam_and_Speed_-_National_Gallery_file.jpg' },
  { id:'f-042', title:'干し草車',                 artist:'ジョン・コンスタブル',       year:1821, century:'19世紀', theme:'風景画', museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/john-constable-the-hay-wain', wikiUrl:'https://ja.wikipedia.org/wiki/干し草車', file:'hay_wain.jpg',              src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/John_Constable_-_The_Hay_Wain_%281821%29.jpg/1280px-John_Constable_-_The_Hay_Wain_%281821%29.jpg' },
  { id:'f-043', title:'オフィーリア',             artist:'ジョン・エヴァレット・ミレイ', year:1852, century:'19世紀', theme:'幻想', museum:'テート・ブリテン',         museumUrl:'https://www.tate.org.uk/art/artworks/millais-ophelia-n01506', wikiUrl:'https://ja.wikipedia.org/wiki/オフィーリア_(絵画)', file:'ophelia.jpg',               src:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Ophelia_-_Everett_Millais.jpg/1280px-Ophelia_-_Everett_Millais.jpg' },
  // ─ ドイツ・ロマン派 ─
  { id:'f-044', title:'霧の海の上の旅人',         artist:'カスパー・ダーヴィト・フリードリヒ', year:1818, century:'19世紀', theme:'風景画', museum:'ハンブルク美術館',    museumUrl:'https://www.hamburger-kunsthalle.de/sammlung/werke/wanderer-ueber-dem-nebelmeer', wikiUrl:'https://ja.wikipedia.org/wiki/霧の海の上の旅人', file:'wanderer_fog.jpg',          src:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/800px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg' },
  { id:'f-045', title:'海辺の修道士',             artist:'カスパー・ダーヴィト・フリードリヒ', year:1810, century:'19世紀', theme:'風景画', museum:'旧国立美術館（ベルリン）', museumUrl:'https://www.smb.museum/en/museums-institutions/alte-nationalgalerie/', wikiUrl:'https://ja.wikipedia.org/wiki/海辺の修道士', file:'monk_by_sea.jpg',           src:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Caspar_David_Friedrich_-_Der_M%C3%B6nch_am_Meer_-_Google_Art_Project.jpg/1280px-Caspar_David_Friedrich_-_Der_M%C3%B6nch_am_Meer_-_Google_Art_Project.jpg' },
  // ─ フランス写実・バルビゾン ─
  { id:'f-046', title:'落穂拾い',                 artist:'ジャン＝フランソワ・ミレー', year:1857, century:'19世紀', theme:'日常',   museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/des-glaneuses-902', wikiUrl:'https://ja.wikipedia.org/wiki/落穂拾い_(ミレー)',                   file:'the_gleaners.jpg',          src:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jean-Fran%C3%A7ois_Millet_-_Gleaners_-_Google_Art_Project_2.jpg/1280px-Jean-Fran%C3%A7ois_Millet_-_Gleaners_-_Google_Art_Project_2.jpg' },
  { id:'f-047', title:'晩鐘',                     artist:'ジャン＝フランソワ・ミレー', year:1859, century:'19世紀', theme:'日常',   museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/langelus-14422',   wikiUrl:'https://ja.wikipedia.org/wiki/晩鐘_(ミレー)',                       file:'the_angelus.jpg',           src:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Jean-Fran%C3%A7ois_Millet_-_L%27Ang%C3%A9lus_-_Google_Art_Project.jpg/1280px-Jean-Fran%C3%A7ois_Millet_-_L%27Ang%C3%A9lus_-_Google_Art_Project.jpg' },
  // ─ 印象派・後期印象派 ─
  { id:'f-048', title:'印象・日の出',             artist:'クロード・モネ',             year:1872, century:'19世紀', theme:'風景画', museum:'マルモッタン・モネ美術館', museumUrl:'https://www.marmottan.fr/en/oeuvre/impression-soleil-levant/', wikiUrl:'https://ja.wikipedia.org/wiki/印象・日の出', file:'impression_sunrise.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/1280px-Monet_-_Impression%2C_Sunrise.jpg' },
  { id:'f-049', title:'睡蓮',                     artist:'クロード・モネ',             year:1906, century:'20世紀', theme:'風景画', museum:'シカゴ美術館',             museumUrl:'https://www.artic.edu/artworks/16568',                     wikiUrl:'https://ja.wikipedia.org/wiki/睡蓮_(モネ)',                         file:'water_lilies_monet.jpg',    src:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/1280px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg' },
  { id:'f-050', title:'ルーアン大聖堂・陽光',     artist:'クロード・モネ',             year:1894, century:'19世紀', theme:'風景画', museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/la-cathedrale-de-rouen-le-portail-et-la-tour-saint-romain-plein-soleil-14367', wikiUrl:'https://ja.wikipedia.org/wiki/ルーアン大聖堂_(モネ)', file:'rouen_cathedral.jpg',      src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Claude_Monet_-_The_Portal_of_Rouen_Cathedral_in_Morning_Light.jpg/800px-Claude_Monet_-_The_Portal_of_Rouen_Cathedral_in_Morning_Light.jpg' },
  { id:'f-051', title:'ラ・グルヌイエール',       artist:'クロード・モネ',             year:1869, century:'19世紀', theme:'日常',   museum:'メトロポリタン美術館',     museumUrl:'https://www.metmuseum.org/art/collection/search/437127',  wikiUrl:'https://ja.wikipedia.org/wiki/ラ・グルヌイエール_(モネ)',             file:'la_grenouillere.jpg',       src:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Claude_Monet_-_La_Grenouill%C3%A8re.jpg/1280px-Claude_Monet_-_La_Grenouill%C3%A8re.jpg' },
  { id:'f-052', title:'ムーラン・ド・ラ・ギャレットの舞踏会', artist:'ピエール＝オーギュスト・ルノワール', year:1876, century:'19世紀', theme:'日常', museum:'オルセー美術館', museumUrl:'https://www.musee-orsay.fr/en/artworks/bal-du-moulin-de-la-galette-125211', wikiUrl:'https://ja.wikipedia.org/wiki/ムーラン・ド・ラ・ギャレットの舞踏会', file:'moulin_galette.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg/1280px-Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg' },
  { id:'f-053', title:'舟遊びの昼食',             artist:'ピエール＝オーギュスト・ルノワール', year:1881, century:'19世紀', theme:'日常', museum:'フィリップス・コレクション', museumUrl:'https://www.phillipscollection.org/works/1611', wikiUrl:'https://ja.wikipedia.org/wiki/舟遊びの昼食', file:'luncheon_boating.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg/1280px-Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg' },
  { id:'f-054', title:'オランピア',               artist:'エドゥアール・マネ',         year:1863, century:'19世紀', theme:'人物画', museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/olympia-712',       wikiUrl:'https://ja.wikipedia.org/wiki/オランピア_(マネ)',                   file:'olympia.jpg',               src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg/1280px-Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg' },
  { id:'f-055', title:'草上の昼食',               artist:'エドゥアール・マネ',         year:1863, century:'19世紀', theme:'日常',   museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/le-dejeuner-sur-lherbe-884', wikiUrl:'https://ja.wikipedia.org/wiki/草上の昼食_(マネ)', file:'dejeuner_herbe.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Edouard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe_-_Google_Art_Project.jpg/1280px-Edouard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe_-_Google_Art_Project.jpg' },
  { id:'f-056', title:'笛を吹く少年',             artist:'エドゥアール・マネ',         year:1866, century:'19世紀', theme:'人物画', museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/le-fifre-885',     wikiUrl:'https://ja.wikipedia.org/wiki/笛を吹く少年',                         file:'the_fifer.jpg',             src:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/%C3%89douard_Manet_-_Le_Fifre_%281866%29.jpg/800px-%C3%89douard_Manet_-_Le_Fifre_%281866%29.jpg' },
  { id:'f-057', title:'バレエの稽古',             artist:'エドガー・ドガ',             year:1874, century:'19世紀', theme:'日常',   museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/la-classe-de-danse-725', wikiUrl:'https://ja.wikipedia.org/wiki/バレエの稽古_(ドガ、オルセー美術館)', file:'ballet_class_degas.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Degas_-_The_Ballet_Class.JPG/1280px-Degas_-_The_Ballet_Class.JPG' },
  { id:'f-058', title:'アブサンを飲む人',         artist:'エドガー・ドガ',             year:1876, century:'19世紀', theme:'日常',   museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/dans-un-cafe-736', wikiUrl:'https://ja.wikipedia.org/wiki/アブサンを飲む人',                     file:'absinthe_drinker.jpg',      src:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Edgar_Degas_-_In_a_Caf%C3%A9_-_Google_Art_Project_2.jpg/800px-Edgar_Degas_-_In_a_Caf%C3%A9_-_Google_Art_Project_2.jpg' },
  { id:'f-059', title:'グラン・ジャット島の日曜日の午後', artist:'ジョルジュ・スーラ', year:1886, century:'19世紀', theme:'日常', museum:'シカゴ美術館',              museumUrl:'https://www.artic.edu/artworks/27992',                     wikiUrl:'https://ja.wikipedia.org/wiki/グラン・ジャット島の日曜日の午後',   file:'grande_jatte.jpg',          src:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884-86.jpg/1280px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884-86.jpg' },
  { id:'f-060', title:'アニエールの水浴',         artist:'ジョルジュ・スーラ',         year:1884, century:'19世紀', theme:'日常',   museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/georges-seurat-bathers-at-asnieres', wikiUrl:'https://ja.wikipedia.org/wiki/アニエールの水浴', file:'bathers_asnieres.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Georges_Seurat_-_Bathers_at_Asni%C3%A8res_-_National_Gallery%2C_London.jpg/1280px-Georges_Seurat_-_Bathers_at_Asni%C3%A8res_-_National_Gallery%2C_London.jpg' },
  { id:'f-061', title:'パリの街路、雨の日',       artist:'ギュスターヴ・カイユボット', year:1877, century:'19世紀', theme:'風景画', museum:'シカゴ美術館',             museumUrl:'https://www.artic.edu/artworks/20684',                     wikiUrl:'https://ja.wikipedia.org/wiki/パリの街路、雨の日',                   file:'paris_rainy_day.jpg',       src:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Gustave_Caillebotte_-_Paris_Street%3B_Rainy_Day_-_Google_Art_Project.jpg/1280px-Gustave_Caillebotte_-_Paris_Street%3B_Rainy_Day_-_Google_Art_Project.jpg' },
  { id:'f-062', title:'タヒチの女たち',           artist:'ポール・ゴーギャン',         year:1891, century:'19世紀', theme:'人物画', museum:'オルセー美術館',           museumUrl:'https://www.musee-orsay.fr/en/artworks/sur-la-plage-14363', wikiUrl:'https://ja.wikipedia.org/wiki/タヒチの女たち', file:'tahitian_women.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Paul_Gauguin_-_Tahitian_Women_on_the_Beach.jpg/1280px-Paul_Gauguin_-_Tahitian_Women_on_the_Beach.jpg' },
  { id:'f-063', title:'我々はどこから来たのか',   artist:'ポール・ゴーギャン',         year:1898, century:'19世紀', theme:'幻想',   museum:'ボストン美術館',           museumUrl:'https://collections.mfa.org/objects/32558',               wikiUrl:'https://ja.wikipedia.org/wiki/我々はどこから来たのか_我々は何者か_我々はどこへ行くのか', file:'gauguin_where.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Paul_Gauguin_-_D%27ou_venons-nous.jpg/1280px-Paul_Gauguin_-_D%27ou_venons-nous.jpg' },
  { id:'f-064', title:'タヒチ・イア・オラナ・マリア', artist:'ポール・ゴーギャン',     year:1891, century:'19世紀', theme:'人物画', museum:'メトロポリタン美術館',     museumUrl:'https://www.metmuseum.org/art/collection/search/438821',  wikiUrl:'https://ja.wikipedia.org/wiki/イア・オラナ・マリア',                 file:'ia_orana_maria.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Paul_Gauguin_-_Ia_Orana_Maria_%28Hail_Mary%29.jpg/800px-Paul_Gauguin_-_Ia_Orana_Maria_%28Hail_Mary%29.jpg' },
  { id:'f-065', title:'カード遊びをする人々',     artist:'ポール・セザンヌ',           year:1895, century:'19世紀', theme:'日常',   museum:'メトロポリタン美術館',     museumUrl:'https://www.metmuseum.org/art/collection/search/435868',  wikiUrl:'https://ja.wikipedia.org/wiki/カード遊びをする人々',                 file:'card_players_cezanne.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Paul_C%C3%A9zanne_-_The_Card_Players_-_Google_Art_Project.jpg/1280px-Paul_C%C3%A9zanne_-_The_Card_Players_-_Google_Art_Project.jpg' },
  { id:'f-066', title:'大水浴図',                 artist:'ポール・セザンヌ',           year:1906, century:'20世紀', theme:'人物画', museum:'フィラデルフィア美術館',   museumUrl:'https://www.philamuseum.org/collection/object/103608',    wikiUrl:'https://ja.wikipedia.org/wiki/大水浴図',                             file:'large_bathers_cezanne.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Paul_Cezanne_-_The_Large_Bathers.jpg/1280px-Paul_Cezanne_-_The_Large_Bathers.jpg' },
  { id:'f-067', title:'ムーラン・ルージュにて',   artist:'アンリ・ド・トゥールーズ＝ロートレック', year:1892, century:'19世紀', theme:'日常', museum:'シカゴ美術館', museumUrl:'https://www.artic.edu/artworks/61128', wikiUrl:'https://ja.wikipedia.org/wiki/ムーラン・ルージュにて', file:'moulin_rouge_lautrec.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/At_the_Moulin_Rouge%2C_1892-95%2C_by_Henri_de_Toulouse-Lautrec.jpg/1024px-At_the_Moulin_Rouge%2C_1892-95%2C_by_Henri_de_Toulouse-Lautrec.jpg' },
  // ─ ゴッホ ─
  { id:'f-068', title:'星月夜',                   artist:'フィンセント・ファン・ゴッホ', year:1889, century:'19世紀', theme:'風景画', museum:'ニューヨーク近代美術館', museumUrl:'https://www.moma.org/collection/works/79802',             wikiUrl:'https://ja.wikipedia.org/wiki/星月夜',                               file:'starry_night.jpg',          src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg' },
  { id:'f-069', title:'ひまわり',                 artist:'フィンセント・ファン・ゴッホ', year:1888, century:'19世紀', theme:'静物',  museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/vincent-van-gogh-sunflowers', wikiUrl:'https://ja.wikipedia.org/wiki/ひまわり_(ゴッホ)', file:'sunflowers_vangogh.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vincent_Willem_van_Gogh_127.jpg/800px-Vincent_Willem_van_Gogh_127.jpg' },
  { id:'f-070', title:'アイリス',                 artist:'フィンセント・ファン・ゴッホ', year:1889, century:'19世紀', theme:'静物',  museum:'ゲッティ美術館',         museumUrl:'https://www.getty.edu/art/collection/object/103JNP',       wikiUrl:'https://ja.wikipedia.org/wiki/アイリス_(ゴッホ)',                   file:'irises_vangogh.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Irises-Vincent_van_Gogh.jpg/1280px-Irises-Vincent_van_Gogh.jpg' },
  { id:'f-071', title:'包帯した耳の自画像',       artist:'フィンセント・ファン・ゴッホ', year:1889, century:'19世紀', theme:'人物画', museum:'コートールド・ギャラリー', museumUrl:'https://courtauld.ac.uk/people/van-gogh-vincent/',        wikiUrl:'https://ja.wikipedia.org/wiki/包帯をした自画像',                     file:'vangogh_bandaged_ear.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/VanGogh_Self-Portrait_with_Bandaged_Ear.jpg/800px-VanGogh_Self-Portrait_with_Bandaged_Ear.jpg' },
  { id:'f-072', title:'麦わら帽子の自画像',       artist:'フィンセント・ファン・ゴッホ', year:1887, century:'19世紀', theme:'人物画', museum:'メトロポリタン美術館',   museumUrl:'https://www.metmuseum.org/art/collection/search/436532',  wikiUrl:'https://ja.wikipedia.org/wiki/ファン・ゴッホの自画像',               file:'vangogh_straw_hat.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Vincent_van_Gogh_-_Self-Portrait_with_Straw_Hat_-_Metropolitan_Museum_of_Art.jpg/800px-Vincent_van_Gogh_-_Self-Portrait_with_Straw_Hat_-_Metropolitan_Museum_of_Art.jpg' },
  // ─ 北欧・表現主義 ─
  { id:'f-073', title:'叫び',                     artist:'エドヴァルド・ムンク',       year:1893, century:'19世紀', theme:'人物画', museum:'ノルウェー国立美術館',     museumUrl:'https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939', wikiUrl:'https://ja.wikipedia.org/wiki/叫び_(エドヴァルド・ムンク)', file:'the_scream.jpg',            src:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/800px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg' },
  // ─ アメリカ ─
  { id:'f-074', title:'アメリカン・ゴシック',     artist:'グラント・ウッド',           year:1930, century:'20世紀', theme:'人物画', museum:'シカゴ美術館',             museumUrl:'https://www.artic.edu/artworks/6565',                     wikiUrl:'https://ja.wikipedia.org/wiki/アメリカン・ゴシック',                 file:'american_gothic.jpg',       src:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/800px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg' },
  { id:'f-075', title:'デラウェア川を渡るワシントン', artist:'エマニュエル・ロイツェ',  year:1851, century:'19世紀', theme:'歴史画', museum:'メトロポリタン美術館',   museumUrl:'https://www.metmuseum.org/art/collection/search/11417',   wikiUrl:'https://ja.wikipedia.org/wiki/デラウェア川を渡るワシントン',         file:'washington_crossing.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Washington_Crossing_the_Delaware_by_Emanuel_Leutze%2C_MMA-NYC%2C_1851.jpg/1280px-Washington_Crossing_the_Delaware_by_Emanuel_Leutze%2C_MMA-NYC%2C_1851.jpg' },
  { id:'f-076', title:'マダムX',                 artist:'ジョン・シンガー・サージェント', year:1884, century:'19世紀', theme:'人物画', museum:'メトロポリタン美術館', museumUrl:'https://www.metmuseum.org/art/collection/search/12127',   wikiUrl:'https://ja.wikipedia.org/wiki/マダムX_(絵画)',                       file:'madame_x.jpg',              src:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/John_Singer_Sargent_-_Mrs._Pierre_Gautreau_%28Madame_X%29.jpg/800px-John_Singer_Sargent_-_Mrs._Pierre_Gautreau_%28Madame_X%29.jpg' },
  { id:'f-077', title:'画家の母（灰色と黒のアレンジメント）', artist:'ジェームズ・マクニール・ホイッスラー', year:1871, century:'19世紀', theme:'人物画', museum:'オルセー美術館', museumUrl:'https://www.musee-orsay.fr/en/artworks/arrangement-en-gris-et-noir-no-1-14373', wikiUrl:'https://ja.wikipedia.org/wiki/灰色と黒のアレンジメント第1番', file:'whistlers_mother.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Whistlers_Mother_high_res.jpg/1024px-Whistlers_Mother_high_res.jpg' },
  { id:'f-078', title:'馬の市',                   artist:'ロザ・ボヌール',             year:1855, century:'19世紀', theme:'動物',   museum:'メトロポリタン美術館',     museumUrl:'https://www.metmuseum.org/art/collection/search/435702',  wikiUrl:'https://ja.wikipedia.org/wiki/馬の市_(絵画)',                         file:'horse_fair.jpg',            src:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Rosa_Bonheur_-_The_Horse_Fair_-_Google_Art_Project.jpg/1280px-Rosa_Bonheur_-_The_Horse_Fair_-_Google_Art_Project.jpg' },
  // ─ サルバドール・ダリ ─
  { id:'f-079', title:'記憶の固執',               artist:'サルバドール・ダリ',         year:1931, century:'20世紀', theme:'幻想',   museum:'ニューヨーク近代美術館',   museumUrl:'https://www.moma.org/collection/works/79018',             wikiUrl:'https://ja.wikipedia.org/wiki/記憶の固執',                           file:'persistence_memory.jpg',    src:'https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg' },
  // ─ ニコラ・プッサン ─
  { id:'f-080', title:'サビーニーの女たちの略奪', artist:'ニコラ・プッサン',           year:1637, century:'17世紀', theme:'歴史画', museum:'メトロポリタン美術館',     museumUrl:'https://www.metmuseum.org/art/collection/search/437329',  wikiUrl:'https://ja.wikipedia.org/wiki/サビニーの女たちの略奪_(プッサン)',    file:'rape_sabines.jpg',          src:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/The_Rape_of_the_Sabine_Women-_Nicolas_Poussin-MBA_Lyon_-_2006-09-22.jpg/1280px-The_Rape_of_the_Sabine_Women-_Nicolas_Poussin-MBA_Lyon_-_2006-09-22.jpg' },
  { id:'f-081', title:'アルカディアにも我あり',   artist:'ニコラ・プッサン',           year:1637, century:'17世紀', theme:'神話',   museum:'ルーヴル美術館',           museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010065608', wikiUrl:'https://ja.wikipedia.org/wiki/Et_in_Arcadia_ego',                    file:'arcadia.jpg',               src:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Nicolas_Poussin_-_Et_in_Arcadia_ego_%281637%E2%80%9338%29_-_WGA18458.jpg/1280px-Nicolas_Poussin_-_Et_in_Arcadia_ego_%281637%E2%80%9338%29_-_WGA18458.jpg' },
  // ─ 17世紀フランス ─
  { id:'f-082', title:'占い師',                   artist:'ジョルジュ・ド・ラ・トゥール', year:1639, century:'17世紀', theme:'日常', museum:'メトロポリタン美術館',     museumUrl:'https://www.metmuseum.org/art/collection/search/436838',  wikiUrl:'https://ja.wikipedia.org/wiki/占い師_(ラ・トゥール)',                 file:'fortune_teller.jpg',        src:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Georges_de_La_Tour_-_The_Fortune_Teller%2C_probably_1630s.jpg/800px-Georges_de_La_Tour_-_The_Fortune_Teller%2C_probably_1630s.jpg' },
  // ─ ルーベンス ─
  { id:'f-083', title:'キリストの昇架',           artist:'ピーテル・パウル・ルーベンス', year:1610, century:'17世紀', theme:'宗教画', museum:'アントワープ大聖堂',      museumUrl:'https://www.onze-lieve-vrouwekathedraal.be/en/collection/the-raising-of-the-cross/', wikiUrl:'https://ja.wikipedia.org/wiki/キリストの昇架', file:'raising_of_cross.jpg',     src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Rubens_Kreuzaufrichtung_Antwerpen.jpg/800px-Rubens_Kreuzaufrichtung_Antwerpen.jpg' },
  // ─ ロセッティ・ミレイ（ラファエル前派）─
  { id:'f-084', title:'オフィーリア',             artist:'ジョン・エヴァレット・ミレイ', year:1852, century:'19世紀', theme:'幻想', museum:'テート・ブリテン',         museumUrl:'https://www.tate.org.uk/art/artworks/millais-ophelia-n01506', wikiUrl:'https://ja.wikipedia.org/wiki/オフィーリア_(絵画)', file:'ophelia.jpg',               src:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Ophelia_-_Everett_Millais.jpg/1280px-Ophelia_-_Everett_Millais.jpg' },
  // ─ 19世紀フランス・アカデミズム ─
  { id:'f-085', title:'ヴィーナスの誕生（カバネル）', artist:'アレクサンドル・カバネル', year:1863, century:'19世紀', theme:'神話', museum:'オルセー美術館',          museumUrl:'https://www.musee-orsay.fr/en/artworks/la-naissance-de-venus-14440', wikiUrl:'https://ja.wikipedia.org/wiki/ヴィーナスの誕生_(カバネル)', file:'birth_venus_cabanel.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Alexandre_Cabanel_-_The_Birth_of_Venus_-_Google_Art_Project_2.jpg/1280px-Alexandre_Cabanel_-_The_Birth_of_Venus_-_Google_Art_Project_2.jpg' },
  // ─ パオロ・ウッチェッロ ─
  { id:'f-086', title:'聖ゲオルギウスと竜',       artist:'パオロ・ウッチェッロ',       year:1456, century:'15世紀', theme:'宗教画', museum:'ナショナル・ギャラリー', museumUrl:'https://www.nationalgallery.org.uk/paintings/paolo-uccello-saint-george-and-the-dragon', wikiUrl:'https://ja.wikipedia.org/wiki/聖ゲオルギウスと竜_(ウッチェッロ)', file:'saint_george_dragon.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Paolo_Uccello_023.jpg/1024px-Paolo_Uccello_023.jpg' },
  // ─ フラ・アンジェリコ ─
  { id:'f-087', title:'受胎告知（フラ・アンジェリコ）', artist:'フラ・アンジェリコ',  year:1440, century:'15世紀', theme:'宗教画', museum:'サン・マルコ美術館',     museumUrl:'https://www.museodiocesanofirenze.it/en/',                wikiUrl:'https://ja.wikipedia.org/wiki/受胎告知_(フラ・アンジェリコ)',         file:'annunciation_angelico.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/FraAngelico_Annunciation_%28cell_3%29.jpg/1280px-FraAngelico_Annunciation_%28cell_3%29.jpg' },
  // ─ マンテーニャ ─
  { id:'f-088', title:'聖マグダラのマリアと聖家族', artist:'アンドレア・マンテーニャ', year:1500, century:'16世紀', theme:'宗教画', museum:'メトロポリタン美術館',   museumUrl:'https://www.metmuseum.org/art/collection/search/436967',  wikiUrl:'https://ja.wikipedia.org/wiki/アンドレア・マンテーニャ',              file:'mantegna_holy_family.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Andrea_Mantegna_-_The_Holy_Family_with_Saint_Mary_Magdalen_-_Google_Art_Project.jpg/800px-Andrea_Mantegna_-_The_Holy_Family_with_Saint_Mary_Magdalen_-_Google_Art_Project.jpg' },
  // ─ ジョルジュ・セーラ（新印象派）─
  { id:'f-089', title:'ポーズするモデルたち',     artist:'ジョルジュ・スーラ',         year:1888, century:'19世紀', theme:'人物画', museum:'バーンズ・ファンデーション', museumUrl:'https://collection.barnesfoundation.org/objects/7648',    wikiUrl:'https://ja.wikipedia.org/wiki/ポーズするモデルたち',                 file:'models_seurat.jpg',         src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Les_Poseuses%2C_Ensemble_%28Petite_version%29%2C_Georges_Seurat%2C_1888.jpg/1280px-Les_Poseuses%2C_Ensemble_%28Petite_version%29%2C_Georges_Seurat%2C_1888.jpg' },
  // ─ ヤン・ファン・エイク ─
  { id:'f-090', title:'ヘントの祭壇画（子羊への礼拝）', artist:'ヤン・ファン・エイク', year:1432, century:'15世紀', theme:'宗教画', museum:'シント・バーフ大聖堂',  museumUrl:'https://www.sintbaafskathedraal.be/en/ghent-altarpiece/',  wikiUrl:'https://ja.wikipedia.org/wiki/ヘントの祭壇画',                       file:'ghent_altarpiece.jpg',      src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Retable_de_l%27Agneau_mystique.jpg/1024px-Retable_de_l%27Agneau_mystique.jpg' },
  // ─ ヤーコブ・ファン・ロイスダール ─
  { id:'f-091', title:'유대人の墓',               artist:'ヤーコブ・ファン・ロイスダール', year:1655, century:'17世紀', theme:'風景画', museum:'ドレスデン絵画館',       museumUrl:'https://www.skd.museum/en/',                              wikiUrl:'https://ja.wikipedia.org/wiki/ヤーコブ・ファン・ロイスダール',        file:'jewish_cemetery.jpg',       src:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Ruisdael_JudenfriedhofinDresden.jpg/1280px-Ruisdael_JudenfriedhofinDresden.jpg' },
  // ─ ジョン・シンガー・サージェント ─
  { id:'f-092', title:'カーネーション、リリー、リリー、ローズ', artist:'ジョン・シンガー・サージェント', year:1886, century:'19世紀', theme:'日常', museum:'テート・ブリテン', museumUrl:'https://www.tate.org.uk/art/artworks/sargent-carnation-lily-lily-rose-n01615', wikiUrl:'https://ja.wikipedia.org/wiki/ジョン・シンガー・サージェント', file:'carnation_lily_rose.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Carnation%2C_Lily%2C_Lily%2C_Rose_%28John_Singer_Sargent%2C_1885-86%29.jpg/800px-Carnation%2C_Lily%2C_Lily%2C_Rose_%28John_Singer_Sargent%2C_1885-86%29.jpg' },
  // ─ ヴィルヘルム・ハンマースホイ ─
  { id:'f-093', title:'室内（ストランガーデ30番地）', artist:'ヴィルヘルム・ハンマースホイ', year:1899, century:'19世紀', theme:'日常', museum:'オルドロップゴー美術館',  museumUrl:'https://ordrupgaard.dk/en/',                              wikiUrl:'https://ja.wikipedia.org/wiki/ヴィルヘルム・ハンマースホイ',          file:'hammershoi_interior.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Hammershoi_interior_1899.jpg/800px-Hammershoi_interior_1899.jpg' },
  // ─ ナルキッソス ─
  { id:'f-094', title:'ナルキッソス',             artist:'カラヴァッジョ',             year:1599, century:'17世紀', theme:'神話',   museum:'バルベリーニ宮殿',         museumUrl:'https://www.barberinicorsini.org/en/opera/narcissus/',    wikiUrl:'https://ja.wikipedia.org/wiki/ナルキッソス_(カラヴァッジョ)',         file:'narcissus_caravaggio.jpg',  src:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Narcissus-Caravaggio_%281594-96%29_edited.jpg/800px-Narcissus-Caravaggio_%281594-96%29_edited.jpg' },
  // ─ ホルバイン ─
  { id:'f-095', title:'ヘルマン・フォン・ヴェーディヒの肖像', artist:'ハンス・ホルバイン（子）', year:1532, century:'16世紀', theme:'人物画', museum:'メトロポリタン美術館', museumUrl:'https://www.metmuseum.org/art/collection/search/436658', wikiUrl:'https://ja.wikipedia.org/wiki/ハンス・ホルバイン_(子)', file:'holbein_wedigh.jpg',         src:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Hans_Holbein_the_Younger_-_Hermann_von_Wedigh_III_-_Google_Art_Project.jpg/800px-Hans_Holbein_the_Younger_-_Hermann_von_Wedigh_III_-_Google_Art_Project.jpg' },
  // ─ フラゴナール ─
  { id:'f-096', title:'ブランコ',                 artist:'ジャン＝オノレ・フラゴナール', year:1767, century:'18世紀', theme:'日常', museum:'ウォレス・コレクション',   museumUrl:'https://www.wallacecollection.org/collection/the-swing/', wikiUrl:'https://ja.wikipedia.org/wiki/ブランコ_(フラゴナール)',               file:'the_swing_fragonard.jpg',   src:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Fragonard%2C_The_Swing.jpg/800px-Fragonard%2C_The_Swing.jpg' },
  // ─ ラファエロ ─
  { id:'f-097', title:'小椅子の聖母',             artist:'ラファエロ・サンティ',       year:1514, century:'16世紀', theme:'宗教画', museum:'ピッティ宮殿',             museumUrl:'https://www.uffizi.it/en/pitti-palace',                   wikiUrl:'https://ja.wikipedia.org/wiki/小椅子の聖母',                         file:'madonna_chair.jpg',         src:'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Raffaello%2C_madonna_della_seggiola.jpg/800px-Raffaello%2C_madonna_della_seggiola.jpg' },
  // ─ ヤン・ステーン ─
  { id:'f-098', title:'病気の女',                 artist:'ヤン・ステーン',             year:1663, century:'17世紀', theme:'日常',   museum:'アムステルダム国立美術館', museumUrl:'https://www.rijksmuseum.nl/en/collection/SK-C-239',       wikiUrl:'https://ja.wikipedia.org/wiki/ヤン・ステーン',                       file:'sick_woman_steen.jpg',      src:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Jan_Steen_-_The_sick_woman.jpg/800px-Jan_Steen_-_The_sick_woman.jpg' },
  // ─ ジャン＝バティスト＝カミーユ・コロー ─
  { id:'f-099', title:'モルトフォンテーヌの思い出', artist:'ジャン＝バティスト＝カミーユ・コロー', year:1864, century:'19世紀', theme:'風景画', museum:'ルーヴル美術館', museumUrl:'https://collections.louvre.fr/en/ark:/53355/cl010062975', wikiUrl:'https://ja.wikipedia.org/wiki/ジャン＝バティスト＝カミーユ・コロー', file:'corot_souvenir.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Corot_Souvenir_of_Mortefontaine.jpg/1280px-Corot_Souvenir_of_Mortefontaine.jpg' },
  // ─ テオドール・ルソー ─
  { id:'f-100', title:'冬の夕暮れの森',           artist:'テオドール・ルソー',         year:1867, century:'19世紀', theme:'風景画', museum:'メトロポリタン美術館',     museumUrl:'https://www.metmuseum.org/art/collection/search/438816',  wikiUrl:'https://ja.wikipedia.org/wiki/テオドール・ルソー_(画家)',             file:'forest_winter_rousseau.jpg', src:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Th%C3%A9odore_Rousseau_-_The_Forest_in_Winter_at_Sunset.jpg/1280px-Th%C3%A9odore_Rousseau_-_The_Forest_in_Winter_at_Sunset.jpg' },
];

async function main() {
  console.log(`=== download-famous.js ===`);
  console.log(`対象: ${FAMOUS100.length}件`);

  const failed = [];
  for (let i = 0; i < FAMOUS100.length; i++) {
    const item = FAMOUS100[i];
    const dest = path.join(OUT_IMG, item.file);
    try {
      await download(item.src, dest);
      const size = fs.statSync(dest).size;
      if (size < 5000) throw new Error(`小さすぎる (${size}B)`);
      console.log(`[${i+1}/${FAMOUS100.length}] OK ${item.file} (${Math.round(size/1024)}KB)`);
    } catch (e) {
      console.error(`[${i+1}/${FAMOUS100.length}] FAIL ${item.file}: ${e.message}`);
      failed.push({ ...item, error: e.message });
    }
    await sleep(400);
  }

  // 成功したものだけでJSONを生成
  const succeeded = FAMOUS100.filter(item => {
    const dest = path.join(OUT_IMG, item.file);
    return fs.existsSync(dest) && fs.statSync(dest).size > 5000;
  });

  const json = {
    generated: new Date().toISOString(),
    total: succeeded.length,
    paintings: succeeded.map(item => ({
      id:        item.id,
      title:     item.title,
      artist:    item.artist,
      year:      item.year,
      century:   item.century,
      theme:     item.theme,
      museum:    item.museum,
      museumUrl: item.museumUrl,
      wikiUrl:   item.wikiUrl,
      image:     `/images/famous/${item.file}`,
      isFamous:  true,
    }))
  };

  fs.writeFileSync(OUT_JSON, JSON.stringify(json, null, 2), 'utf8');
  console.log(`\n=== 完了: ${succeeded.length}/${FAMOUS100.length}件成功 ===`);
  console.log(`JSON: ${OUT_JSON}`);
  if (failed.length > 0) {
    console.error(`失敗${failed.length}件:`, failed.map(f => f.file));
  }
}

main().catch(e => { console.error(e); process.exit(1); });
